# Generated by Django 3.0.7 on 2024-04-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20240229_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
